### ISSUE TITLE
Change database pull-request tracking by organization configuration

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquibot/automated-merging#2]
The watcher should use GitHub API to go through all opened pull-requests instead of relying on a database. The main advantage is that we could get rid of the database which sole purpose is to keep track of the pull-requests to watch.

              It keeps track of the pull request to check updates for. Eventually, we could replace that with a list of organizations inside the configuration, which would allow us to totally remove the need for a database.

_Originally posted by @gentlementlegen in https://github.com/ubiquibot/automated-merging/pull/1#discussion_r1694058679_

**Comment by 0x4007** [comment]
Looks like more than four hours of work so we'll add credit
